# Generated by Django 2.2 on 2020-11-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VDI_Consulting_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
